%%
%%  Copyright (C) 2019--2024 SDUFEACM <https://github.com/sdufeacm>
%% 
%%  This work may be distributed and/or modified under the
%%  conditions of the LaTeX Project Public License, either
%%  version 1.3c of this license or (at your option) any later
%%  version. The latest version of this license is in:
%% 
%%    http://www.latex-project.org/lppl.txt
%% 
%%  and version 1.3 or later is part of all distributions of
%%  LaTeX version 2008 or later.
%% 
%%  This work has the LPPL maintenance status `maintained'.
%% 
%%  The Current Maintainer of this work is Shilei Lu <i@mslxl.com>.
%%

\NeedsTeXFormat{LaTeX2e}
\RequirePackage{expl3}
\ProvidesExplClass {sdufe-thesis} {2024-03-27} {v0.0.1}
  {Thesis template for Shandong University of Finance and Economics}
